{
 "title": "Kafka Clients - Consumers [z-score metrics]",
 "description": "Kafka Clients - Consumers [z-score metrics]",
 "tags": [
  "client",
  "consumer",
  "kafka"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "kafka_consumer_request_total [z-score]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(\njob:kafka_consumer_request_total:rate1m -\njob:kafka_consumer_request_total:rate1m:avg_over_time_1h\n) /  job:kafka_consumer_request_total:rate1m:stddev_over_time_1h"
    }
   ]
  },
  {
   "title": "kafka_consumergroup_group_lag [z-score]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(\njob:kafka_consumergroup_group_lag -\njob:kafka_consumergroup_group_lag:avg_over_time_1h\n) /  job:kafka_consumergroup_group_lag:stddev_over_time_1h"
    }
   ]
  },
  {
   "title": "kafka_consumer_request_total [1m rate]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "job:kafka_consumer_request_total:rate1m"
    }
   ]
  },
  {
   "title": "kafka_consumergroup_group_lag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "job:kafka_consumergroup_group_lag"
    }
   ]
  },
  { "title": "kafka_consumer_request_total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } }
 ]
}