{
 "title": "Kafka Clients - Consumers",
 "description": "Kafka Clients - Consumers",
 "tags": [
  "kafka",
  "consumer",
  "client"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "env", "label": "env", "query": { "query": "label_values(env)" } },
   {
    "name": "client_id",
    "query": {
     "query": "label_values(kafka_consumer_response_rate{env=\"$env\"}, client_id)"
    }
   },
   { "name": "group_id", "label": "group_id", "query": { "query": "label_values(group)" } },
   { "name": "topic", "label": "topic", "query": { "query": "label_values(topic)" } }
  ]
 },
 "panels": [
  {
   "title": "Commit rate",
   "type": "stat",
   "description": "The number of commit calls per second .",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_commit_rate{client_id=~\"$client_id\", env=\"$env\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average fetch throttle time",
   "type": "stat",
   "description": "The average time in ms a request was throttled by a broker.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_fetch_throttle_time_avg{client_id=~\"$client_id\", env=\"$env\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed auth rate",
   "type": "stat",
   "description": "Rate of failed authentication attempts\n",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_failed_authentication_total{env=\"$env\",client_id=~\"$client_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Rebalance rate per hour",
   "type": "stat",
   "description": "The number of total rebalance events per hour, both successful and unsuccessful rebalance attempts.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_rebalance_rate_per_hour{client_id=~\"$client_id\", env=\"$env\"} + kafka_consumer_coordinator_failed_rebalance_rate_per_hour{client_id=~\"$client_id\", env=\"$env\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consumer group lag in records ",
   "type": "graph",
   "description": "Offset lag per consumer group, summed by topic",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (kafka_consumergroup_group_lag{group=~\"${group_id}\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer group lag in seconds ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) ((kafka_consumergroup_group_lag_seconds{group=~\"${group_id}\"} > 0))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Consumer Commit Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Commit latency average",
   "type": "graph",
   "description": "The average time taken for a commit request",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_commit_latency_avg{client_id=~\"$client_id\", env=\"$env\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Commit rate",
   "type": "graph",
   "description": "The number of commit calls per second .",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_commit_rate{client_id=~\"$client_id\", env=\"$env\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Consumer Fetch Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Fetch request rate",
   "type": "graph",
   "description": "The number of fetch requests per second.\n",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_consumer_fetch_manager_fetch_total{client_id=~\"$client_id\", env=\"$env\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Fetch size avg",
   "type": "graph",
   "description": "The average number of bytes fetched per request for a topic",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_fetch_size_avg{topic=~\"$topic\", client_id=~\"$client_id\", env=\"$env\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Fetch latency average",
   "type": "graph",
   "description": "The average time taken for a fetch request.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_fetch_latency_avg{client_id=~\"$client_id\", env=\"$env\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Bytes consumed rate",
   "type": "graph",
   "description": "The average number of bytes consumed per second\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_consumer_fetch_manager_bytes_consumed_total{topic=~\"$topic\", client_id=~\"$client_id\", env=\"$env\"}[$__rate_interval])",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Rate of records consumed",
   "type": "graph",
   "description": "The average number of records consumed per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_consumer_fetch_manager_records_consumed_total{topic=~\"$topic\", client_id=\"$client_id\", env=\"$env\"}[$__rate_interval])",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Bytes consumed rate per topic",
   "type": "graph",
   "description": "The average number of bytes consumed per topic per second.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_fetch_manager_bytes_consumed_total{topic!=\"\", client_id=\"$client_id\", env=\"$env\"}[$__rate_interval])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Rate of records consumed per topic",
   "type": "graph",
   "description": "The average number of records consumed per second per topic.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic, instance) (rate(kafka_consumer_fetch_manager_records_consumed_total{topic!=\"\", client_id=\"$client_id\", env=\"$env\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}-{{topic}}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Current connection count",
   "type": "graph",
   "description": "Number of simultaneous connections\n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_connection_count_total",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Node reponse rate",
   "type": "graph",
   "description": "response rate per node\n",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_node_response_rate{client_id=~\"$client_id\", env=\"$env\"}"
    }
   ]
  }
 ]
}