{
 "title": "Kafka Clients - Producers",
 "description": "Kafka Clients - Producers",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "env", "query": { "query": "label_values(env)" } },
   {
    "name": "client_id",
    "query": {
     "query": "label_values(kafka_app_info_start_time_ms{env=\"$env\"}, client_id)"
    }
   },
   {
    "name": "topic",
    "query": {
     "query": "label_values(kafka_producer_topic_byte_total{env=\"$env\", client_id=\"$client_id\"}, topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Retry rate",
   "type": "stat",
   "description": "The average per-second number of retried record sends for a topic. An increase could signal connectivity problems from the application to the broker. ",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_producer_record_retry_rate{env=\"$env\",client_id=~\"$client_id\"}",
     "legendFormat": " {{instance}}"
    }
   ]
  },
  {
   "title": "Record error rate",
   "type": "stat",
   "description": "The average per-second number of record sends that resulted in errors.\n",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(kafka_producer_record_error_total{env=\"$env\",client_id=~\"$client_id\"}[$__rate_interval])",
     "legendFormat": " {{instance}}"
    }
   ]
  },
  {
   "title": "Free buffer space",
   "type": "stat",
   "description": "The total amount of buffer memory that is not being used (either unallocated or in the free list).",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_producer_buffer_available_bytes{env=\"$env\",client_id=~\"$client_id\"}",
     "legendFormat": "Buffer bytes available"
    }
   ]
  },
  {
   "title": "Produce request throttle average",
   "type": "stat",
   "description": "The average time in ms a request was throttled by a broker.",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_producer_produce_throttle_time_avg{env=\"$env\",client_id=~\"$client_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Compression rate",
   "type": "stat",
   "description": "The average compression rate of record batches for a topic, defined as the average ratio of the compressed batch size over the uncompressed size.",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_producer_compression_rate_avg{env=\"$env\",client_id=~\"$client_id\"}"
    }
   ]
  },
  {
   "title": "Produce request latency",
   "type": "graph",
   "description": "The average request latency in ms.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_request_latency_avg{env=\"$env\",client_id=~\"$client_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Record queue time",
   "type": "graph",
   "description": "The average time in ms record batches spent in the send buffer.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_record_queue_time_avg{env=\"$env\",client_id=~\"$client_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed authentication rate",
   "type": "graph",
   "description": "The rate of failed authentication per seconds\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_producer_failed_authentication_total{env=\"$env\",client_id=~\"$client_id\"}[$__rate_interval])",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Outgoing byte rate",
   "type": "graph",
   "description": "The average number of bytes sent per second to the broker.\n",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_producer_outgoing_byte_total{env=\"$env\",client_id=~\"$client_id\"}[$__rate_interval])",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Outgoing byte rate per topic",
   "type": "graph",
   "description": "The average number of bytes sent per second to the broker per topic.\n",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_producer_topic_byte_total{env=\"$env\",client_id=~\"$client_id\"}[$__rate_interval])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Outgoing messages per second per topic",
   "type": "graph",
   "description": "The average number of messages sent per second to the broker per topic.\n",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "iops", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_producer_topic_record_send_total{}[$__rate_interval])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Outgoing messages per second",
   "type": "graph",
   "description": "The average number of messages sent per second to the broker.\n",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_producer_record_send_total{env=\"$env\",client_id=~\"$client_id\"}[$__rate_interval])",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Batch size average",
   "type": "graph",
   "description": "The average number of bytes sent per partition per-request.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_batch_size_avg{env=\"$env\",client_id=~\"$client_id\"}",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Request in flight",
   "type": "graph",
   "description": "The current number of in-flight requests awaiting a response.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_requests_in_flight{env=\"$env\",client_id=~\"$client_id\"}",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Record size average",
   "type": "graph",
   "description": "The average record size",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_record_size_avg{env=\"$env\",client_id=~\"$client_id\"}",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  { "title": "Produce Request metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Produce request rate",
   "type": "graph",
   "description": "The average number of requests sent per second to the broker.\n",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_producer_request_total{env=\"$env\",client_id=~\"$client_id\"}[$__rate_interval])",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Produce request size average",
   "type": "graph",
   "description": "The average number of records per request.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_request_size_avg{env=\"$env\",client_id=~\"$client_id\"}",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Produce response rate",
   "type": "graph",
   "description": "The average number of response received per second to the broker.\n",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_producer_response_total{env=\"$env\",client_id=~\"$client_id\"}[$__rate_interval])",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Connection rate",
   "type": "graph",
   "description": "The current number of active connections.\n",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_producer_connection_count_total{env=\"$env\",client_id=~\"$client_id\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Connection creation rate",
   "type": "graph",
   "description": "New connections established per second in the window.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_connection_creation_rate{env=\"$env\",client_id=~\"$client_id\"}"
    }
   ]
  },
  {
   "title": "Connection close rate",
   "type": "graph",
   "description": "Connections closed per second in the window.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_connection_close_rate{env=\"$env\",client_id=~\"$client_id\"}"
    }
   ]
  },
  {
   "title": "IO Ratio",
   "type": "graph",
   "description": "The fraction of time the I/O thread spent doing I/O.\n",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_io_ratio{env=\"$env\",client_id=~\"$client_id\"}"
    }
   ]
  },
  {
   "title": "IO Wait time average",
   "type": "graph",
   "description": "The average length of time the I/O thread spent waiting for a socket ready for reads or writes in nanoseconds.\n",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 52 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_io_wait_time_ns_avg{env=\"$env\",client_id=~\"$client_id\"}"
    }
   ]
  },
  {
   "title": "IO Time average",
   "type": "graph",
   "description": "The average length of time for I/O per select call in nanoseconds.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_io_time_ns_avg{env=\"$env\",client_id=~\"$client_id\"}"
    }
   ]
  },
  {
   "title": "IO Wait Ratio",
   "type": "graph",
   "description": "The fraction of time the I/O thread spent waiting.\n",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_io_wait_ratio{env=\"$env\",client_id=~\"$client_id\"}"
    }
   ]
  },
  {
   "title": "Select Rate",
   "type": "graph",
   "description": "Number of times the I/O layer checked for new I/O to perform per second.\n",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_select_rate{env=\"$env\",client_id=~\"$client_id\"}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "API Version",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 5, "x": 2, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_app_info_start_time_ms{env=\"$env\",client_id=~\"$client_id\",kafka_version!=\"\"}",
     "legendFormat": "{{kafka_version}}"
    }
   ]
  },
  {
   "title": "Metadata max age",
   "type": "graph",
   "description": "The age in seconds of the current producer metadata being used.",
   "gridPos": { "h": 9, "w": 12, "x": 7, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_metadata_age{env=\"$env\",client_id=~\"$client_id\"}",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  }
 ]
}